---
stages:
  - test
  - cleanup

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - docker -v
  - python3 -V
  - python3 -m venv ..
  - source ../bin/activate

molecule:
  stage: test
  tags:
    - shell
  script:
    - pip install docker molecule
    - molecule test
