---
- name: log into private registry
  docker_login:
    username: '{{ item.username }}'
    password: '{{ item.password }}'
    api_version: '{{ item.api_version | default("auto") }}'
    ca_cert: '{{ item.ca_cert | default(omit) }}'
    client_cert: '{{ item.client_cert | default(omit) }}'
    client_key: '{{ item.client_key | default(omit) }}'
    config_path: '{{ item.config_path | default(omit) }}'
    debug: '{{ item.debug | default("no") }}'
    docker_host: '{{ item.docker_host | default(omit) }}'
    email: '{{ item.email | default(omit) }}'
    reauthorize: '{{ item.reauthorize | default("no") }}'
    registry_url: '{{ item.registry_url | default(omit) }}'
    ssl_version: '{{ item.ssl_version | default(omit) }}'
    state: '{{ item.state | default("present") }}'
    timeout: '{{ item.timeout | default("60") }}'
    tls: '{{ item.tls | default("no") }}'
    tls_hostname: '{{ item.tls_hostname | default("localhost") }}'
    validate_certs: '{{ item.validate_certs | default(omit) }}'
  no_log: true
  loop: "{{ registries }}"
  when: registries is defined
